### ISSUE TITLE
Not able to fetch package if inside private npm proxy.

### ISSUE THREAD

**Issue by anjum121** [Kikobeats/emojis-list#19]
We have corporate restricted nexus server to manage npm packages when tried to install within corp npm  getting below error 

````
3364 verbose stack Error: 500 javax.servlet.ServletException: org.sonatype.nexus.repository.storage.RetryDeniedException: Reached max retries: 8/8: emojis-list@^2.0.0
3364 verbose stack     at fetch.then.res (/Users/anjum/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
3364 verbose stack     at tryCatcher (/Users/anjum/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
3364 verbose stack     at Promise._settlePromiseFromHandler (/Users/anjum/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
3364 verbose stack     at Promise._settlePromise (/Users/anjum/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
3364 verbose stack     at Promise._settlePromise0 (/Users/anjum/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
3364 verbose stack     at Promise._settlePromises (/Users/anjum/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
3364 verbose stack     at Async._drainQueue (/Users/anjum/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
3364 verbose stack     at Async._drainQueues (/Users/anjum/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
3364 verbose stack     at Immediate.Async.drainQueues (/Users/anjum/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
3364 verbose stack     at runCallback (timers.js:810:20)
3364 verbose stack     at tryOnImmediate (timers.js:768:5)
3364 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)

````
I believe in package.json of emojis-list we need to add ssh something like 

Current 

```` 
"repository": {
    "type": "git",
    "url": "git+https://github.com/kikobeats/emojis-list.git"
  }
````
Expected 

`````
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/kikobeats/emojis-list.git"
  },
`````

This will fix above problem

**Comment by Kikobeats** [comment]
do you test it? happy to accept a PR
